services:
  # run jupyter notebook inside jupyter 
  jupyter-notebook:
    image:  ytin98/522group:latest
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/522group
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64
