name: 522groupenv.yaml
channels:
  - conda-forge
dependencies:
  - pandas
  - python=3.12
  - scikit-learn
  - ucimlrepo
  - jupyter
  - matplotlib
  - altair
  - vegafusion
  - vl-convert-python[version='>=1.8.0']
  - pyarrow
  - conda-lock
  - pandera
  - deepchecks
  - pointblank
prefix: C:\Users\upwaz\miniforge3\envs\522groupenv.yaml
